### ISSUE TITLE
Vite command not working

### ISSUE THREAD

**Issue by matthughes** [gemini-hlsw/lucuma-react#162]
Installed `vite` 3.1.0 via homebrew.  Successfully ran `semanticUIDemo/fastLinkJS`.  But when I try to run the suggested vite command I get:

```
vite -c semantic-ui-demo/vite.config.js

failed to load config from /Users/MHughe008/Opensource/lucuma-react/semantic-ui-demo/vite.config.js
error when starting dev server:
Error: Cannot find module '@vitejs/plugin-react'
Require stack:
- /Users/MHughe008/Opensource/lucuma-react/semantic-ui-demo/vite.config.js
- /opt/homebrew/Cellar/vite/3.1.0/libexec/lib/node_modules/vite/dist/node/chunks/dep-665b0112.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/MHughe008/Opensource/lucuma-react/semantic-ui-demo/vite.config.js:31:35)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at _require.extensions.<computed> [as .js] (file:///opt/homebrew/Cellar/vite/3.1.0/libexec/lib/node_modules/vite/dist/node/chunks/dep-665b0112.js:63438:24)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
```

**Comment by armanbilge** [comment]
Did you run `npm install` ?

**Comment by matthughes** [comment]
Yeah 

```
 npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"^17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @atlaskit/tree@8.6.2
npm ERR! node_modules/@atlaskit/tree
npm ERR!   dev @atlaskit/tree@"^8.6.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/MHughe008/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MHughe008/.npm/_logs/2022-09-08T20_56_46_015Z-debug-0.log
```

Also how are you so fast to respond? :)

**Comment by armanbilge** [comment]
`npm install --force` as it suggests 😛
